### PR TITLE
replace hardcoded sudo command with cubevar_api_superuser variable

### PR DESCRIPTION
**Pull request by bfmartin**
Make the script more portable by replacing hardcoded sudo command

### CODE REVIEW

**Comment by kevgrig** [comment]
Appreciate the PR but I'm not sure I follow. `cubevar_api_superuser` [defaults to nothing](https://github.com/myplaceonline/posixcube/blob/81b1ab113f50cb693715f22ef1feee567c16fa18/posixcube.sh#L592) and it is only [set](https://github.com/myplaceonline/posixcube/blob/81b1ab113f50cb693715f22ef1feee567c16fa18/posixcube.sh#L2939) if [`-S` is specified](https://github.com/myplaceonline/posixcube/blob/81b1ab113f50cb693715f22ef1feee567c16fa18/posixcube.sh#L2438). It's possible to run `posixcube.sh` as non-root (without `-S`) but then the user may want to use `cube_sudo` to run a command as root. Normally, I tend to think that posixcube-based scripts should just use POSIX commands instead of posixcube commands when possible (so I recommend just using `sudo` directly when needed), but `cube_sudo` is designed for the case that the `sudo` command needs access to `posixcube.sh` functions or variables (i.e. if a user runs vanilla `sudo` from the posixcube.sh script, they do not have access to the `posixcube.sh` functions and variables - this is just a side-effect of the design of POSIX `sudo` sub-commands).

**Comment by bfmartin** [comment]
What you say is true, for Linux systems at least.
My situation is a bit different. One of the OS's I run this on is OpenBSD, and it uses the doas command instead of sudo. So a hard-coded sudo command does not work for that OS.

**Comment by freeradical13** [comment]
I see, interesting. I'll think about this some more...

**Comment by kevgrig** [comment]
I see, interesting. I'll think about this some and get back to you...

**Comment by kevgrig** [comment]
I just committed 502da53e163fa5ad16074056dc5a366a45759126 which adds a `-D CMD` option. Let me know if that works. For example:

    posixcube.sh -D doas [...]

By itself, this only affects `cube_sudo`. If `-S` is also specified, the superuser-based commands will also use `CMD`.

**Comment by bfmartin** [comment]
Works very well. Thank you. I will close the PR.

**Comment by kevgrig** [comment]
Cheers. In theory, instead of specifying `-D CMD`, `p_superuser_command` could be auto-detected based on OS (e.g. using the `POSIXCUBE_OS_*` values). I didn't bother to do this because it would require some time and testing and I thought `-D CMD` would be useful in either case and pretty easy to specify.

**Pull request closed without merging**
